
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push tag
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS='["alifnaufalyasin/gits-capstone-project:latest","user/image:'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS='["alifnaufalyasin/gits-capstone-project:latest"]'
          fi
          echo '::set-output name=tags::'$TAGS
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        needs: gen_tags
        with:
          context: ./src
          push: true
          tags: ${{ fromJson(steps.gen_tags.outputs.tags) }}
          labels: ${{ steps.meta.outputs.labels }}
